# Generated by Django 4.1 on 2023-12-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acta",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
            options={
                "db_table": "acta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Campo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "campo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha_vigencia", models.CharField(max_length=10)),
                ("fecha_caducidad", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "contrato",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Crudo",
            fields=[
                (
                    "name",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("gravedad", models.FloatField()),
                ("porcentaje_azufre", models.FloatField()),
                ("precio_promedio", models.IntegerField()),
                ("equivalencia_brent", models.FloatField()),
            ],
            options={
                "db_table": "crudo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=25)),
                ("area", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "departamento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("sexo", models.CharField(max_length=1)),
                ("fecha_ingreso", models.CharField(max_length=10)),
                ("nacimiento", models.CharField(max_length=10)),
                ("salario", models.IntegerField()),
            ],
            options={
                "db_table": "empleado",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HistoriaCarrotanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrotanque_id", models.CharField(max_length=6)),
                ("territorio", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "territorio_id",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("fecha_asignacion", models.DateField(blank=True, null=True)),
                ("empleado", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "db_table": "historia_carrotanque",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Indicador",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("brent", models.FloatField()),
                ("trm", models.FloatField()),
            ],
            options={
                "db_table": "indicador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Oleoducto",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "oleoducto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Operador",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "operador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Territorio",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "territorio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.departamento",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.empleado",
                    ),
                ),
            ],
            options={
                "db_table": "supervisor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Refineria",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=15)),
                ("capacidad_kbpd", models.CharField(max_length=3)),
                (
                    "territorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.territorio",
                    ),
                ),
            ],
            options={
                "db_table": "refineria",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Puerto",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=15)),
                (
                    "territorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.territorio",
                    ),
                ),
            ],
            options={
                "db_table": "puerto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OleoductoAtraviesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estacion", models.CharField(max_length=15)),
                (
                    "oleoducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.oleoducto",
                    ),
                ),
                (
                    "territorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.territorio",
                    ),
                ),
            ],
            options={
                "db_table": "oleoducto_atraviesa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gerente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma", models.CharField(max_length=8)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.empleado",
                    ),
                ),
            ],
            options={
                "db_table": "gerente",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("valor", models.FloatField()),
                ("cantidad_barriles_kbpd", models.FloatField()),
                ("porcentaje_produccion", models.IntegerField()),
                (
                    "acta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.acta",
                    ),
                ),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.campo",
                    ),
                ),
            ],
            options={
                "db_table": "factura",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Contratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.empleado",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.supervisor",
                    ),
                ),
            ],
            options={
                "db_table": "contratista",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Carrotanque",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("capacidad_litros", models.IntegerField()),
                (
                    "territorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.territorio",
                    ),
                ),
            ],
            options={
                "db_table": "carrotanque",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="campo",
            name="crudo_name",
            field=models.ForeignKey(
                db_column="crudo_name",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.crudo",
            ),
        ),
        migrations.AddField(
            model_name="campo",
            name="operador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.operador"
            ),
        ),
        migrations.AddField(
            model_name="campo",
            name="territorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.territorio",
            ),
        ),
        migrations.AddField(
            model_name="acta",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.contrato"
            ),
        ),
        migrations.AddField(
            model_name="acta",
            name="gerente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.gerente"
            ),
        ),
        migrations.AddField(
            model_name="acta",
            name="indicador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.indicador"
            ),
        ),
    ]
