# Generated by Django 4.1 on 2023-12-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiacarrotanque",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
