# Generated by Django 4.1 on 2023-12-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_historiacarrotanque_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oleoductoatraviesa",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
