# Generated by Django 4.1 on 2023-12-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_oleoductoatraviesa_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historiacarrotanque",
            name="empleado",
        ),
    ]
